### ISSUE TITLE
Is there a way to set which is the north and south, east,west on the compass?

### ISSUE THREAD

**Issue by Erchil66** [alihadi5125/smooth_compass#4]
e.g.
SmoothCompass(
 north : - 100 // as my north to identify
 south: 100,
 east: -50,
 west: 50,
),

does it able to set it on the compass?

**Comment by Erchil66** [comment]
I solve at my end i just wanted to manually move it given by esp32. thanks for the package btw.

**Comment by fahadshabeer** [comment]
> I solve at my end i just wanted to manually move it given by esp32. thanks for the package btw.

thank you :) 👍
